services:
  app_medinote:
    build: 
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://172.17.0.1:5432/db_mdn
      DB_USER_NAME: postgres
      DB_PASSWORD: 1234
    restart: always

  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    depends_on:
      - app_medinote
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  my_custom_network:
    driver: bridge