export const LABELS_NOTA_MEDICA = {
    TENSION_ARTERIAL: "Tensión Arterial",
    FRECUENCIA_RESPIRATORIA: "Frecuencia Respiratoria",
    FRECUENCIA_CARDIACA: "Frecuencia Cardíaca",
    SATURACION_O: "Saturación de Oxígeno",
    ALTURA: "Altura",
    TEMPERATURA: "Temperatura",
    PESO: "Peso",

    ESTADO_NEUROLOGICO: "Estado Neurológico",
    EXPLORACION_SUPERIOR: "Exploración Superior",
    ABDOMEN: "Abdomen",
    EXTREMIDADES: "Extremidades",
    PIEL: "Piel",
    TORAX: "Tórax",
    GENITALES: "Genitales",

    IMPRESION_DIAGNOSTICA: "Impresión Diagnóstica",
    ANALISIS_PLAN: "Análisis y Plan",
    PADECIMIENTO_ACTUAL: "Padecimiento Actual",

    // Síntomas generales
    FIEBRE: "Fiebre",
    ASTENIA: "Astenia",
    ADINAMIA: "Adinamia",
    NAUSEA: "Náusea",
    VOMITO: "Vómito",
    PERDIDA_PESO: "Pérdida de Peso",
    CEFÁLEA: "Cefalea",
    OTROS: "Otros",

    // Aparato digestivo
    HALITOSIS: "Halitosis",
    BOCA_SECA: "Boca Seca",
    DISFAGIA: "Disfagia",
    ODINOFAGIA: "Odinofagia",
    PIROSIS: "Pirosis",
    MELENA: "Melena",
    HEMATEMESIS: "Hematemesis",
    FLATULENCIAS: "Flatulencias",
    DIARREA: "Diarrea",
    RECTORRAGIA: "Rectorragia",
    ESTREÑIMIENTO: "Estreñimiento",
    TENESMO: "Tenesmo",
    ACOLIA: "Acolia",
    METEORISMO: "Meteorismo",

    // Aparato respiratorio
    DISNEA: "Disnea",
    TOS: "Tos",
    DISFONIA: "Disfonía",
    ATONIA: "Atonía",
    CIANOSIS: "Cianosis",
    APNEA_SUENO: "Apnea del Sueño",
    RINORREA: "Rinorrea",
    RONQUERA: "Ronquera",
    CONGESTION_NASAL: "Congestión Nasal",
    EPISTAXIS: "Epistaxis",

    // Aparato cardiovascular
    DOLOR_TORACICO: "Dolor Torácico",
    SINCOPE: "Síncope",
    PALPITACIONES: "Palpitaciones",
    DIAFORESIS: "Diaforesis",
    FATIGA: "Fatiga",
    EDEMA: "Edema",
    ANSIEDAD: "Ansiedad",
    DESMAYOS: "Desmayos",

    // Aparato urinario
    INCONTINENCIA: "Incontinencia",
    DISURIA: "Disuria",
    TENESMO_VESICAL: "Tenesmo Vesical",
    HEMATURIA: "Hematuria",
    COLURIA: "Coluria",
    QUILURIA: "Quiluria",
    POLIURIA: "Poliuria",
    ANURIA: "Anuria",
    NICTURIA: "Nicturia",
    INTERMITENCIA_CHORRO: "Intermitencia del Chorro",
    URGENCIA_MICCIONAL: "Urgencia Miccional",
    CHORRO_DEBIL: "Chorro Débil",
    POLAQUIURIA: "Polaquiuria",

    // Sistema nervioso
    VERTIGO: "Vértigo",
    PARESIA: "Paresia",
    DISESTESIAS: "Disestesias",
    PARALISIS: "Parálisis",
    MOVIMIENTOS_ANORMALES: "Movimientos Anormales",
    VISION_BORROSA: "Visión Borrosa",
    AMAUROSIS: "Amaurosis",
    DOLOR_MUSCULAR: "Dolor Muscular",
    ANESTESIA: "Anestesia",
    HIPOESTESIA: "Hipoestesia",
    HIPERESTESIA: "Hiperestesia",
    HIPOACUSIA: "Hipoacusia",
    ANOSMIA: "Anosmia",
    ALTERACION_GUSTO: "Alteración del Gusto",

    // Sistema endocrino
    INTOLERANCIA_FRIO: "Intolerancia al Frío",
    INTOLERANCIA_CALOR: "Intolerancia al Calor",
    LETARGIA: "Letargia",
    POLIDIPSIA: "Polidipsia",
    POLIFAGIA: "Polifagia",
    BRADIPSIQUIA: "Bradipsiquia",
    BRADILALIA: "Bradilalia",
    TAQUICARDIA: "Taquicardia",

    // Aparato musculoesquelético
    MIALGIAS: "Mialgias",
    ARTRALGIAS: "Artralgias",
    CREPITACION: "Crepitación",
    DEBILIDAD_MUSCULAR: "Debilidad Muscular",
    DEFORMIDAD: "Deformidad",
    DISMINUCION_MOVILIDAD: "Disminución de la Movilidad",
    DIFICULTAD_DEAMBULACION: "Dificultad para la Deambulación",

    // Sistema hematológico
    PETEQUIAS: "Petequias",
    EQUIMOSIS: "Equimosis",
    HEMORRAGIAS: "Hemorragias",
    LIPOTIMIA: "Lipotimia",

    // Sistema psiquiátrico
    DELIRIO: "Delirio",
    ALUCINACIONES: "Alucinaciones",
    HIPERSOMNIA: "Hipersomnia",
    INSOMNIO: "Insomnio",
    DEPRESION: "Depresión",
    FOBIAS: "Fobias",
    TOC: "Trastorno Obsesivo-Compulsivo (TOC)",
    ALTERACIONES_PENSAMIENTO: "Alteraciones del Pensamiento",
    PENSAMIENTO_SUICIDA: "Pensamiento Suicida",
};
